### ISSUE TITLE
Button returns empty string for "Varies with device"

### ISSUE THREAD

**Issue by TheLastProject** [cvzi/playshields#16]
Hey there,

Quite a cool project! I've been using this for a while in the README of [Catima](https://github.com/CatimaLoyalty/Android) but it seems to have broken recently for "Varies with device" values on the Google Play Store for `$version` and `$android`.

| App | Version screenshot | JSON | Button |
| - | - | - | - |
| [me.hackerchick.catima](https://play.google.com/store/apps/details?id=me.hackerchick.catima) | ![Varies by device](https://user-images.githubusercontent.com/1885159/174434750-06bcc1b7-26ed-4f66-b699-5453637b72b3.png) | `{"cacheSeconds":3600,"label":"Google Play","message":"","schemaVersion":1}` | ![invalid properties: message](https://img.shields.io/endpoint?url=https%3A%2F%2Fplayshields.herokuapp.com%2Fplay%3Fi%3Dme.hackerchick.catima%26l%3DGoogle%2520Play%26m%3D%24version) |
| [me.hackerchick.raisetoanswer](https://play.google.com/store/apps/details?id=me.hackerchick.raisetoanswer) | ![3.6.5](https://user-images.githubusercontent.com/1885159/174434839-af599256-2cb3-4fb6-8ab5-1cf2226813a6.png) | `{"cacheSeconds":3600,"label":"Google Play","message":"3.6.5","schemaVersion":1}` | ![3.6.5](https://img.shields.io/endpoint?url=https%3A%2F%2Fplayshields.herokuapp.com%2Fplay%3Fi%3Dme.hackerchick.raisetoanswer%26l%3DGoogle%2520Play%26m%3D%24version) |

For example, [me.hackerchick.catima](https://play.google.com/store/apps/details?id=me.hackerchick.catima) contains "Varies with device" under "Version", which causes this error message. Using [me.hackerchick.raisetoanswer](https://play.google.com/store/apps/details?id=me.hackerchick.raisetoanswer) contains "3.6.5" under "Version" and displays fine.

It's not a huge deal for me (I just hardcoded "Varies with device" right now) and I guess you could argue that this is an issue with shields.io instead of this project, but I figured I'd still tell you :)

**Comment by cvzi** [comment]
Thanks for the report. Yes the play store recently changed their website completely. The information is no longer available as HTML on the website, the text is now generated from a cryptic Javascript array. For catima the relevant part is this:
```json
[
    [
        null,
        []
    ],
    [
        [[31,"12"]],
        [null,[]]
    ]
]
```
compared to raisetoanswer:
```json
[
    [
        ["3.6.5"]
    ],
    [
        [[30,"11"]],
        [[[26,"8.0"]]]
    ]
]
```

The version numbers of catima don't seem to appear anywhere else in the HTML of the play store website either. I guess I'll also hardcode a fallback to "Varies with device", it's better than the error message.
